# --- Fonts ---
font_family      CodeNewRoman Nerd Font Propo
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13.0

# --- Glass & Transparency ---
# Уровень прозрачности (0.0 - полностью прозрачный, 1.0 - сплошной)
background_opacity 0.5
# Динамическое изменение прозрачности (если нужно)
dynamic_background_opacity yes

# --- Theme / Colors (Blue & White) ---
background            #0f0f0f
foreground            #f8f8f2
cursor                #0066cc
selection_background  #004c99
selection_foreground  #ffffff

# Colors for terminal (Сине-белая палитра)
color0  #1e1e1e
color8  #545454
color1  #ff5555
color9  #ff6e6e
color2  #50fa7b
color10 #69ff94
color4  #0066cc
color12 #3399ff
color7  #bfbfbf
color15 #ffffff

# --- Window Layout ---
window_padding_width 15
confirm_os_window_close 0

# --- Cursor & Mouse ---
cursor_shape block
shell_integration  enabled
mouse_hide_wait 3.0
